"""create users trees persons relationships

Revision ID: de75b43af2fd
Revises: ad50e71d3964
Create Date: 2026-04-15 20:37:33.198279

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de75b43af2fd'
down_revision: str | None = 'ad50e71d3964'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('trees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility IN ('private','shared','public')", name=op.f('ck_trees_visibility_allowed')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_trees_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trees'))
    )
    op.create_index(op.f('ix_trees_owner_id'), 'trees', ['owner_id'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tree_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_date_approx', sa.String(length=64), nullable=True),
    sa.Column('birth_place', sa.String(length=255), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('death_date_approx', sa.String(length=64), nullable=True),
    sa.Column('death_place', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk_persons_tree_id_trees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons'))
    )
    op.create_index(op.f('ix_persons_full_name'), 'persons', ['full_name'], unique=False)
    op.create_index(op.f('ix_persons_tree_id'), 'persons', ['tree_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tree_id', sa.UUID(), nullable=False),
    sa.Column('person_a_id', sa.UUID(), nullable=False),
    sa.Column('person_b_id', sa.UUID(), nullable=False),
    sa.Column('rel_type', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("rel_type IN ('parent','spouse')", name=op.f('ck_relationships_rel_type_allowed')),
    sa.ForeignKeyConstraint(['person_a_id'], ['persons.id'], name=op.f('fk_relationships_person_a_id_persons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_b_id'], ['persons.id'], name=op.f('fk_relationships_person_b_id_persons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk_relationships_tree_id_trees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationships')),
    sa.UniqueConstraint('tree_id', 'person_a_id', 'person_b_id', 'rel_type', name='relationship_unique')
    )
    op.create_index(op.f('ix_relationships_person_a_id'), 'relationships', ['person_a_id'], unique=False)
    op.create_index(op.f('ix_relationships_person_b_id'), 'relationships', ['person_b_id'], unique=False)
    op.create_index(op.f('ix_relationships_tree_id'), 'relationships', ['tree_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_tree_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_person_b_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_person_a_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_persons_tree_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_full_name'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_trees_owner_id'), table_name='trees')
    op.drop_table('trees')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
